version: '3.2'
services:
    recorder_front:
        image: surveillance_recorder:0.0.2
        build: ./recorder
        depends_on:
            - mysql
        restart: always
        volumes: 
            - ./files:/app/files
            - ./recorder/logs:/app/recorder/logs
        environment:
            - TZ=America/Los_Angeles
            - CONFIG_FILE=config_front.json
            - WEIGHTS_FILE=weights/yolov3.tf
            - APP_ENV=production
        devices:
            - /dev/video0:/dev/video0
        env_file: .env

    recorder_back:
        image: surveillance_recorder:0.0.2
        build: ./recorder
        depends_on:
            - mysql
        restart: always
        volumes:
            - ./files:/app/files
            - ./recorder/logs:/app/recorder/logs
        environment:
            - TZ=America/Los_Angeles
            - CONFIG_FILE=config_back.json
            - WEIGHTS_FILE=weights/yolov3.tf
            - APP_ENV=production
        devices:
            - /dev/video0:/dev/video0
        env_file: .env

    server:
        image: surveillance_server:0.0.2
        build: ./server
        depends_on: 
            - mysql
        environment: 
            FLASK_ENV: ${FLASK_ENV}
        restart: always
        ports: 
            - '5000:5000'
        expose:
            - '5000'
        volumes: 
            - ./server:/app/server
            - ./files:/app/server/static/files
        
    mysql:
        image: mysql:latest
        env_file: .env
        restart: always
        ports: 
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./mysql_data:/var/lib/mysql
        cap_add:
            - SYS_NICE

volumes:
    files:
