version: '3.2'
services: 
    recorder:
        build: ./recorder
        depends_on:
            - mysql
        restart: always
        volumes: 
            - ./files:/app/files
        environment:
            - TZ=America/Los_Angeles
        devices:
            - /dev/video0:/dev/video0
        env_file: .env
    server:
        build: ./server
        depends_on: 
            - mysql
        environment: 
            FLASK_ENV: ${FLASK_ENV}
        restart: always
        ports: 
            - '5000:5000'
        expose:
            - '5000'
        volumes: 
            - ./server:/app/server
            - ./files:/app/server/static/files
        
    mysql:
        image: mysql:latest
        env_file: .env
        restart: always
        ports: 
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./mysql_data:/var/lib/mysql

volumes:
    files:
